name: pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
             python -m pip install --upgrade pip
             pip install pylint
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: ".github/workflows/pylint_requirements.txt"
      - name: Analysing the code with pylint
        run: |
             pylint --disable=line-too-long,invalid-name,unused-wildcard-import,missing-module-docstring,too-many-instance-attributes,fixme,too-many-lines,wildcard-import,too-many-public-methods RFM69
